server:
  port: 8080

spring:
  application:
    name: lunch-lunch

  datasource:
    url: jdbc:postgresql://localhost:5432/lunch-lunch
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev: update | prod: validate hoặc none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect